### ISSUE TITLE
Secure actuator endpoints

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#57]
As a developer, I want to secure the actuator endpoints so that they're not open outside and can't be called without proper authorisation. 

Acceptance Criteria:
1. Make sure to secure the endpoints
2. Check-in with the team (also with the best practices) that which endpoints can be removed so that we don't expose every actuator endpoint.
3. The endpoints are still reachable using proper authorisation (username, password)

Notes:
As an example, see: https://www.amitph.com/how-to-secure-spring-boot-actuator-endpoints/#:~:text=The%20best%20way%20to%20secure,only%20a%20two%2Dstep%20process.

**Comment by Rapter1990** [comment]
@agitrubard @skayikci @emreylmaz @ilkerCelimli @moaydogdu 

To solve the **issue** , we can follow **all these steps** shown below

- Add `Spring Security` and `Actuator` (we already added all them into `pom.xml`)
- Enable all **actuator** endpoints defined in application.yml file 
  ```
   management:  
     endpoints:
        web:
           exposure:
              include: '*'
   ```
- Customize Username and Password shown below
  
  ```
     spring:
        security:
            user:
              name: monitor
              password: monitor123
              roles: ADMIN
   ```
- Configure HttpSecurity shown below

```
@Configuration
@EnableWebSecurity
public class WebSecurity {

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http.authorizeHttpRequests()
            .requestMatchers("/actuator/**").hasRole("ADMIN")
            .anyRequest().authenticated()
            .and()
            .httpBasic();

        return http.build();
    }

}
```

If we cannot use `spring.security.user`, we should determine a **role** giving access to `/actuator` endpoints.

Can you check it?
