### ISSUE TITLE
Revision of Kubernetes

### ISSUE THREAD

**Issue by Rapter1990** [afet-yonetim-sistemi/ays-be#76]
I noticed that the project cannot work with Kuberentes as MySQL configuration cannot be handled with. I devised some codes for that. 
Can you check all these yaml files and test them ? @skayikci @sinanartun 

**configMap.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: ays
  MYSQL_USER: ays
  MYSQL_PASSWORD: ayspass
  MYSQL_ROOT_PASSWORD: ayspass
  MYSQL_ROOT_HOST: '%'
```

**mysql-deployment.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        envFrom:
          - configMapRef:
              name: mysql-config
        ports:
          - containerPort: 3307
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**deployment.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ays-be
  name: ays-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ays-be
  template:
    metadata:
      labels:
        app: ays-be
    spec:
      containers:
      - image: ays/ays-be
        imagePullPolicy: Never
        name: ays-be
        ports:
          - containerPort: 9790
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: development
          - name: AYS_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_USER
          - name: AYS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_PASSWORD
          - name: AYS_DB_URL
            value: jdbc:mysql://mysql:3307/ays
      restartPolicy: OnFailure
      volumes:
        - name: ays-data
          emptyDir: {}

```

**services.yaml**

```
apiVersion: v1
kind: Service
metadata:
  name: ays-be
spec:
  selector:
    app: ays-be
  ports:
    - port: 8080
      targetPort: 9790
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3307
```

Here is the **commands** to show how to run them for **Kubernetes**

```
kubectl apply -f configMap.yaml
kubectl apply -f mysql-deployment.yaml
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
```
