### ISSUE TITLE
Add Grafana and Prometheus in docker-compose and define prometheus.yml for config

### ISSUE THREAD

**Issue by Rapter1990** [afet-yonetim-sistemi/ays-be#92]
We can add **Grafana** and **Prometheus** in **docker-compose** for monitoring and scaling the app.  As **Grafana** detects the **Prometheus**,  `prometheus.yml` should be devised.

Add **Prometheus** endpoints to `application.ym`l file shown below

```
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
```

Here is the `prometheus.yml` file for config shown below. It is located underneath `data/prometheus/config`

```
global:
  scrape_interval: 120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'AYS Backend Project'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['application:9790']
        labels:
          application: 'AYS Backend Project'
```

Here is the updated `docker-compose.yml` file shown below
```

version: "3.9"

services:
  database:
    container_name: database
    image: mysql:8.0
    #    platform: linux/x86_64     # for Intel Chips with WSL2 Enabled
    #    platform: linux/arm64/v8    # for Mac Silicon Chips
    restart: always
    environment:
      MYSQL_DATABASE: ays
      MYSQL_USER: ays
      MYSQL_PASSWORD: ayspass
      MYSQL_ROOT_PASSWORD: ayspass
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - ays-network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "9790:9790"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - AYS_DB_USERNAME=ays
      - AYS_DB_PASSWORD=ayspass
      - AYS_DB_URL=jdbc:mysql://host.docker.internal:3307/ays
    depends_on:
      - database
    networks:
      - ays-network
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - ays-network
  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - ays-network

networks:
  ays-network:

```

@skayikci @agitrubard @emreylmaz @burcubayik @microgenius @moaydogdu @ilkerCelimli Can you check it?
